import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { NOTE_TEMPLATE_OPTIONS } from "../shared/noteTemplates.js";

const repoRoot = resolve(import.meta.dirname, "..");
const workspaceRoot = resolve(repoRoot, "../..");
const promptsDir = join(workspaceRoot, "medical_notes_prompts");
const outputPath = join(repoRoot, "worker", "src", "notePromptTemplates.js");

const promptTemplates = Object.fromEntries(
  NOTE_TEMPLATE_OPTIONS.map((template) => [
    template.key,
    {
      file: template.file,
      text: readFileSync(join(promptsDir, template.file), "utf8"),
    },
  ]),
);

writeFileSync(
  outputPath,
  [
    "// Generated by scripts/sync_note_prompts.mjs from ../../medical_notes_prompts.",
    "// Do not edit this file by hand; edit the prompt files and rerun the sync script.",
    `export const NOTE_PROMPT_TEMPLATES = ${JSON.stringify(promptTemplates, null, 2)};`,
    "",
  ].join("\n"),
  "utf8",
);

console.log(`Wrote ${outputPath}`);
